# Train an ML model and upload the output of the training process

pool:
vmImage: 'Ubuntu 16.04'

steps:
- task: AzureCLI@1
displayName: 'Install Azure ML extension'
inputs:
    azureSubscription: larrymltest
    scriptLocation: scriptPath
    scriptPath: TrainOnLocalEnv.py

- task: PublishBuildArtifacts@1
inputs:
    pathtoPublish: '$(Build.SourcesDirectory)/output.txt'
    artifactName: model_output
