# Python Django
# Test a Django project on multiple versions of Python.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python
pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: 3.5
    architecture: 'x64'
- script: |
    pip install azureml
    pip install azureml.core
  displayName: 'Install prerequisites'

- task: AzureCLI@1
  displayName: 'Train on VM'
  inputs:
    azureSubscription: miprasad
    scriptLocation: scriptPath
    scriptPath: TrainOnVM.py

- task: AzureCLI@1
  displayName: 'Evaluate Production Model with Newly trained model'
  inputs:
    azureSubscription: miprasad
    scriptLocation: scriptPath
    scriptPath: EvaluateModel.py

- script: |
    python code/testing/data_test.py data/diabetes_bad_schema.csv
  displayName: 'Test Schema'
